version: '2'
services:
  service: # Main
    build: .
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./src:/home/node/app/src
      - ./scripts:/home/node/app/scripts
      - ./package.json:/home/node/app/package.json
      - ./.nycrc:/home/node/app/.nycrc
    ports:
      - 80:8000
      - 9222:9222
